spring:
  rabbitmq:
    host: 192.168.32.128
    port: 5672
    username: root
    password: root
    publisher-confirms: true  #  消息发送到交换机确认机制,是否确认回调
    publisher-returns: true
  devtools:
    restart:
      enabled: false
server:
  port: 8080
